// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK9JODCYjPWZB0BYVcpx5ZSYYqkrlCi44',
    appId: '1:291111193719:web:0d22d3f2e6c223366d0a72',
    messagingSenderId: '291111193719',
    projectId: 'mytodo-flutte',
    authDomain: 'mytodo-flutte.firebaseapp.com',
    storageBucket: 'mytodo-flutte.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX2PW6h4nRM416oJrNq24hi8c_3w4Euqw',
    appId: '1:291111193719:android:4fbf62acd37eaa9b6d0a72',
    messagingSenderId: '291111193719',
    projectId: 'mytodo-flutte',
    storageBucket: 'mytodo-flutte.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ8iALhqlgm5dFnHedcggE53ltZQhYRSI',
    appId: '1:291111193719:ios:0a29ba81bf2daf936d0a72',
    messagingSenderId: '291111193719',
    projectId: 'mytodo-flutte',
    storageBucket: 'mytodo-flutte.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ8iALhqlgm5dFnHedcggE53ltZQhYRSI',
    appId: '1:291111193719:ios:0a29ba81bf2daf936d0a72',
    messagingSenderId: '291111193719',
    projectId: 'mytodo-flutte',
    storageBucket: 'mytodo-flutte.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK9JODCYjPWZB0BYVcpx5ZSYYqkrlCi44',
    appId: '1:291111193719:web:c56a6e568dddbf5c6d0a72',
    messagingSenderId: '291111193719',
    projectId: 'mytodo-flutte',
    authDomain: 'mytodo-flutte.firebaseapp.com',
    storageBucket: 'mytodo-flutte.appspot.com',
  );

}